FROM justb4/jmeter:5.3
LABEL application="Orama"
LABEL maintainer="University of Brasilia"
LABEL component="Benchmarker"
WORKDIR "/benchmarker"
COPY . /benchmarker
ENTRYPOINT ["tail", "-f", "/dev/null"]
